In [1]:
import numpy as np
arr = np.array([1,2,3,6,4,5])
print(np.flip(arr))

[5 4 6 3 2 1]


In [2]:
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flattened_array = array1.flatten() # no np.flatten()
print(flattened_array)

[1 2 3 2 4 5 1 2 3]


In [3]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
counts_x = np.bincount(x)
print(np.argmax(counts_x))
counts_y = np.bincount(y)
print(np.argmax(counts_y))

1
1


In [4]:
import numpy as np

gfg = np.matrix('4 1 9; 12 3 1; 4 5 6')
total_sum = np.sum(gfg)
print(f"Sum of all elements: {total_sum}")
row_sum = np.sum(gfg,axis=1)
print(f"Sum of row-wise elements: {row_sum}")
col_sum = np.sum(gfg,axis=0)
print(f"Sum of column-wise elements : {col_sum}")

Sum of all elements: 45
Sum of row-wise elements: [[14]
 [16]
 [15]]
Sum of column-wise elements : [[20  9 16]]


In [5]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
trace = np.trace(n_array)
print(trace)
eigenvalues, _ = np.linalg.eig(n_array)
print(eigenvalues)
_, eigenvectors = np.linalg.eig(n_array)
print(eigenvectors)
inverse = np.linalg.inv(n_array)
print(inverse)
det = np.linalg.det(n_array)
print(det)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [6]:
p = np.array([[1, 2],[2, 3]])
q = np.array([[4, 5],[6, 7]])
C = np.dot(p,q)
p_flat = p.flatten()
q_flat = q.flatten()
data = np.vstack((p_flat, q_flat))
cov_matrix = np.cov(data)
print(f"cov_matrix : {cov_matrix} & matrix multiplication : {C}")

cov_matrix : [[0.66666667 1.        ]
 [1.         1.66666667]] & matrix multiplication : [[16 19]
 [26 31]]


In [7]:
p = np.array([[1,2],[2,3],[4,5]])
q = np.array([[4,5,1],[6,7,2]])
C = np.dot(p,q)
p_flat = p.flatten()
q_flat = q.flatten()
data = np.vstack((p_flat, q_flat))
cov_matrix = np.cov(data)
print(f"cov_matrix : {cov_matrix} & matrix multiplication : {C}")

cov_matrix : [[2.16666667 0.23333333]
 [0.23333333 5.36666667]] & matrix multiplication : [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [8]:
import numpy as np

x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])

# Inner product (matrix multiplication) - fix with transpose on y
res1 = np.dot(x, y.T)

# Outer product (correct)
res2 = np.outer(x.flatten(), y.flatten())

# Cartesian product of all elements - flatten both before repeat/tile
res3 = np.transpose([
    np.repeat(x.flatten(), len(y.flatten())),
    np.tile(y.flatten(), len(x.flatten()))
])

print(f"Inner Product : \n{res1}\n")
print(f"Outer Product : \n{res2}\n")
print(f"Cartesian Product : \n{res3}\n")

Inner Product : 
[[17 52]
 [13 62]]

Outer Product : 
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product : 
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]



In [9]:
# Part (a)
array = np.array([[1, -2, 3], [-4, 5, -6]])

# (i)
print("Element-wise absolute value:\n", np.abs(array))

# (ii) Percentiles
print("Flattened percentiles (25,50,75):", [np.percentile(array.flatten(), p) for p in [25, 50, 75]])
print("Column percentiles (25,50,75):\n", [np.percentile(array, p, axis=0) for p in [25, 50, 75]])
print("Row percentiles (25,50,75):\n", [np.percentile(array, p, axis=1) for p in [25, 50, 75]])

# (iii) Mean, Median, Std
print("Flattened Mean, Median, Std:", np.mean(array), np.median(array), np.std(array))
print("Column-wise Mean, Median, Std:\n", np.mean(array, axis=0), np.median(array, axis=0), np.std(array, axis=0))
print("Row-wise Mean, Median, Std:\n", np.mean(array, axis=1), np.median(array, axis=1), np.std(array, axis=1))

# Part (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:\n", np.floor(a))
print("Ceil:\n", np.ceil(a))
print("Truncated:\n", np.trunc(a))
print("Rounded:\n", np.round(a))

Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]
Flattened percentiles (25,50,75): [np.float64(-3.5), np.float64(-0.5), np.float64(2.5)]
Column percentiles (25,50,75):
 [array([-2.75, -0.25, -3.75]), array([-1.5,  1.5, -1.5]), array([-0.25,  3.25,  0.75])]
Row percentiles (25,50,75):
 [array([-0.5, -5. ]), array([ 1., -4.]), array([2. , 0.5])]
Flattened Mean, Median, Std: -0.5 -0.5 3.8622100754188224
Column-wise Mean, Median, Std:
 [-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
Row-wise Mean, Median, Std:
 [ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]
Floor:
 [-2. -2. -1.  0.  1.  1.  3.]
Ceil:
 [-1. -1. -0.  1.  2.  2.  3.]
Truncated:
 [-1. -1. -0.  0.  1.  1.  3.]
Rounded:
 [-2. -2. -0.  0.  2.  2.  3.]


In [10]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = np.partition(array, 4)[:4]
largest_5 = np.partition(array, -5)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_4)
print("5 largest elements:", largest_5)

array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers_only = array_b[array_b == array_b.astype(int)]
floats_only = array_b[array_b != array_b.astype(int)]

print("Integer elements only:", integers_only)
print("Float elements only:", floats_only)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]
Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]
